"""empty message

Revision ID: 672fcba00140
Revises: 6f6130f378c6
Create Date: 2025-12-08 16:37:40.893460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672fcba00140'
down_revision = '6f6130f378c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('email_queue_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('email_queue_ibfk_1'), 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('recipient_email')

    # ### end Alembic commands ###
