"""Fix borrow table: remove 'ad' column

Revision ID: 70f01d38dd4e
Revises: daf6021e04f0
Create Date: 2025-12-17 04:18:36.347792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70f01d38dd4e'
down_revision = 'daf6021e04f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.alter_column('ceza',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('first_delay_at')

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('email_queue_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('email_queue_ibfk_1'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_delay_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('ceza',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
