"""yazar tablosu eklendi

Revision ID: daf6021e04f0
Revises: 672fcba00140
Create Date: 2025-12-13 13:03:48.742274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daf6021e04f0'
down_revision = '672fcba00140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('email_queue_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'kullanici'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'kullanici'"))

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('email_queue_ibfk_1'), 'user', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
