"""ad sütunu guncellendi

Revision ID: e2cc5bdac6f0
Revises: 70f01d38dd4e
Create Date: 2025-12-17 19:27:08.514790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2cc5bdac6f0'
down_revision = '70f01d38dd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_column('ad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
